@extends('admin/contentLayoutMaster')

@section('title', 'Income List')

@section('vendor-style')
    {{-- Page Css files --}}
    <link rel="stylesheet" href="{{ asset(mix('vendors/css/forms/select/select2.min.css')) }}">
    <link rel="stylesheet" href="{{ asset(mix('vendors/css/tables/datatable/dataTables.bootstrap5.min.css')) }}">
    <link rel="stylesheet" href="{{ asset(mix('vendors/css/tables/datatable/responsive.bootstrap5.min.css')) }}">
    <link rel="stylesheet" href="{{ asset(mix('vendors/css/tables/datatable/buttons.bootstrap5.min.css')) }}">
    <link rel="stylesheet" href="{{ asset(mix('vendors/css/tables/datatable/rowGroup.bootstrap5.min.css')) }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/7.2.0/sweetalert2.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.js"></script>
@endsection

@section('page-style')
    {{-- Page Css files --}}
    <link rel="stylesheet" href="{{ asset(mix('css/base/plugins/forms/form-validation.css')) }}">
@endsection

@section('content')
<style>
   table {
    counter-reset: section;
  }
  .count:before {
    counter-increment: section;
    content: counter(section);
  }
</style>
<section>
    <div class="card">
        <div class="card-header">
            <h4 class="card-title">Generate Pdf Report</h4>
        </div>
        <div class="card-body">
            <form action="/admin/report" method="get">
                @csrf
                <div class="row">
                    <div class="col-md-5 offset-1">
                        <label for="" class="mt-1">From</label>
                        <input type="date" name="from_date" id="from_date" class="form-control" placeholder="From Date"  />
                    </div>
                    <div class="col-md-5">
                        <label for="" class="mt-1">To</label>
                        <input type="date" name="to_date" id="to_date" class="form-control" placeholder="To Date"  />
                    </div>
                    <div class="col-md-5 offset-1">
                        <label for="" class="mt-1">Generated by</label>
                        @if (Auth::check())
                        <select class="form-select" name="genrated_by">
                            <option value="{{Auth::user()->username}}">{{Auth::user()->username}}</option>
                        </select>
                        @endif
                    </div>
                </div>
                <div class="col-md-4 offset-5 mt-1">
                    <button type="submit" class="btn btn-success">Search</button>
                </div>
            </form>
        </div>
    </div>
</section>    
<!-- Basic Tables start -->
<div class="row" id="basic-table">
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        <h4 class="card-title">Income Report</h4>
      </div>
      <div class="table-responsive width-95-per mx-auto">
        <div class="dt-buttons float-end"  style="margin-left: 20px; margin-top: 14px;">
        <button class="dt-button add-new btn btn-success waves-effect 
            waves-float waves-light" tabindex="0"aria-controls="DataTables_Table_0" type="button"
            onclick="window.location.href='/admin/incomef'">
            <span>Add New</span>
        </button>
        </div>
        <table class="table datatable">
          <thead>
              <tr>
                <th>Id</th>
                <th>Month</th>
                <th>Revenue</th>
                <th>Expences</th>
                <th>Profit</th>
                <th>Loss</th>
              </tr>
          </thead>
          <tbody>
              @foreach($user as $data)
              <tr>
                <td class="count"></td>
                <td>{{date("d M Y", strtotime($data->month))}}</td>
                <td>{{$data->revenue}}</td>
                <td>{{$data->expences}}</td>
                <td>{{$data->profit}}</td>
                <td>{{$data->loss}}</td>
              </tr>
              @endforeach
          </tbody>
        </table>
      </div>
    </div>
    <!-- Basic Tables end -->
@endsection
@section('vendor-script')
    {{-- Vendor js files --}}
    <script src="{{ asset(mix('vendors/js/forms/select/select2.full.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/jquery.dataTables.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/dataTables.bootstrap5.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/dataTables.responsive.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/responsive.bootstrap5.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/datatables.buttons.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/jszip.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/pdfmake.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/vfs_fonts.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/buttons.html5.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/buttons.print.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/dataTables.rowGroup.min.js')) }}">
    </script>
    <script src="{{ asset(mix('vendors/js/forms/validation/jquery.validate.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/forms/cleave/cleave.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/forms/cleave/addons/cleave-phone.us.js')) }}"></script>
@endsection

<script type="text/javascript" charset="utf8" src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js">
</script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.3/js/dataTables.bootstrap5.min.js
"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/select/1.3.3/js/dataTables.select.min.js
"></script>
<script src="{{ asset('swal/sweetalert.js') }}"></script>
<!-- Filter data-->

<script>
    $(document).ready(function() {
        $('.datatable').DataTable({
            select: true
        });
    });
</script>
<script>
$(function() {
    $('.toggle-class').change(function() {
      var status = $(this).prop('checked') == true ? 1 : 0;
      var id = $(this).data('id');

      $.ajax({
        type: "GET",
        dataType: "json",
        url: '/admin/incomestatus',
        data: {
          'status': status,
          'id': id
        },
        success: function(data) {
          Swal.fire({
            position: 'top-end',
            icon: 'success',
            title: 'Status Changed',
            showConfirmButton: false,
            timer: 1100
          });
        }
      });
    })
});
</script>
